import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2024-10-11T15:35:01.775335012+02:00[Europe/Rome]
 * <br>
*  The generated test suite contains 7 tests
 * <br>
*  Covered targets: 7
 * <br>
*  Used time: 0h 10m 0s
 * <br>
*  Needed budget for current results: 56%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
*/
public class EvoMaster_others_Test {

    
    private static String baseUrlOfSut = "http://localhost:8080/";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    @Test(timeout = 60000)
    public void test_0() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/authors/Tsl/works.json?limit=330")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/authors/Tsl/works\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_1() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/books/64g0Iwc")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/books/64g0Iwc\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_2() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/isbn/1Y4SnHE")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/isbn/1Y4SnHE\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_3() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/volumes/brief/98CXqTc8y/HLAWWMKZ8g.json")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    @Test(timeout = 60000)
    public void test_4() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/covers/yBHzT30b/K3ZcMNZzO-BWXtCY8D.jpg")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/covers/yBHzT30b/K3ZcMNZzO-BWXtCY8D.jpg\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_5() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/authors/BwzhBKpu.json")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/authors/BwzhBKpu\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_6() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/works/25")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/works/25\"}"));
    }


}
