import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2024-10-11T14:19:52.287792098+02:00[Europe/Rome]
 * <br>
*  The generated test suite contains 7 tests
 * <br>
*  Covered targets: 7
 * <br>
*  Used time: 0h 30m 0s
 * <br>
*  Needed budget for current results: 50%
 * <br>
*  This file contains test cases that represent failed calls, but not indicative of faults.
*/
public class EvoMaster_others_Test {

    
    private static String baseUrlOfSut = "http://localhost:8080/";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    @Test(timeout = 60000)
    public void test_0() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/isbn/ANW5jJlnpP21u")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("text/html");
    }
    
    
    @Test(timeout = 60000)
    public void test_1() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/authors/H/works.json?limit=577")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/authors/H/works\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_2() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/covers/tvqN5AR/JOGHXKi4pwdSzf-WtK.jpg")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/covers/tvqN5AR/JOGHXKi4pwdSzf-WtK.jpg\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_3() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/books/n6srmrKe")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/books/n6srmrKe\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_4() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/volumes/brief/wyNbVKyLR1/G_.json?callback=tK61ic")
                .then()
                .statusCode(404)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    @Test(timeout = 60000)
    public void test_5() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/authors/IfYJhD7.json")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/authors/IfYJhD7\"}"));
    }
    
    
    @Test(timeout = 60000)
    public void test_6() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/works/WnQJmH6")
                .then()
                .statusCode(404)
                .assertThat()
                .body(containsString("{\"error\": \"notfound\", \"key\": \"/works/WnQJmH6\"}"));
    }


}
