import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-01-09T18:09:51.564190624+01:00[Europe/Rome]
 * <br>
*  The generated test suite contains 26 tests
 * <br>
*  Covered targets: 78
 * <br>
*  Used time: 0h 10m 1s
 * <br>
*  Needed budget for current results: 99%
 * <br>
*  This file contains test cases that are likely to indicate faults.
*/
public class EvoMaster_faults_Test {

    
    private static String baseUrlOfSut = "http://localhost:8080/";
    
    
    @BeforeClass
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    @Test(timeout = 60000)
    public void test_0_with500() throws Exception {
        
        // Fault100. HTTP Status 500. DELETE:/api/route/{id}
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/route/434")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No class com.app.entity.Route entity with id 434 exists!"))
                .body("'path'", containsString("/api/route/434"));
    }
    
    
    @Test(timeout = 60000)
    public void test_1_with500() throws Exception {
        
        // Fault100. HTTP Status 500. DELETE:/api/flight/{id}
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/flight/7925170492904279843")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No class com.app.entity.Flight entity with id 7925170492904279843 exists!"))
                .body("'path'", containsString("/api/flight/7925170492904279843"));
    }
    
    
    @Test(timeout = 60000)
    public void test_2_with500() throws Exception {
        
        // Fault100. HTTP Status 500. PUT:/api/flight
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"bDQmTpZa\", " + 
                    " \"arrivalDateTime\": \"1935-01-10T25:43:53\", " + 
                    " \"quotaFilled\": 70, " + 
                    " \"quotaFilledPercentage\": 227, " + 
                    " \"route\": { " + 
                    " \"id\": 286, " + 
                    " \"name\": \"PCx\", " + 
                    " \"departureAirport\": { " + 
                    " \"name\": \"gn95fHXU8H\", " + 
                    " \"capacity\": 78, " + 
                    " \"location\": \"ucSb_k\" " + 
                    " }, " + 
                    " \"arrivalAirport\": { " + 
                    " \"id\": 737, " + 
                    " \"name\": \"zVFo7ddxx_gHma0\", " + 
                    " \"capacity\": 876 " + 
                    " } " + 
                    " }, " + 
                    " \"plane\": { " + 
                    " \"name\": \"OZNR1\", " + 
                    " \"numberOfSeats\": 82, " + 
                    " \"company\": { " + 
                    " \"name\": \"kDHKKpvUKz7IE\" " + 
                    " } " + 
                    " } " + 
                    " } ")
                .put(baseUrlOfSut + "/api/flight")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.app.entity.Flight.plane -> com.app.entity.Plane; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : com.app.entity.Flight.plane -> com.app.entity.Plane"))
                .body("'path'", containsString("/api/flight"));
    }
    
    
    @Test(timeout = 60000)
    public void test_3_with500() throws Exception {
        
        // Fault100. HTTP Status 500. DELETE:/api/company/{id}
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/company/-5683324706572101336")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No class com.app.entity.Company entity with id -5683324706572101336 exists!"))
                .body("'path'", containsString("/api/company/-5683324706572101336"));
    }
    
    
    @Test(timeout = 60000)
    public void test_4_with500() throws Exception {
        
        // Fault100. HTTP Status 500. POST:/api/route
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"kDEJ\", " + 
                    " \"departureAirportId\": 963, " + 
                    " \"arrivalAirportId\": 941 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/route")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to find com.app.entity.Airport with id 963"))
                .body("'path'", containsString("/api/route"));
    }
    
    
    @Test(timeout = 60000)
    public void test_5_with500() throws Exception {
        
        // Fault100. HTTP Status 500. POST:/api/ticket
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"ticketCode\": \"W\", " + 
                    " \"flightId\": 755 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/ticket")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("query did not return a unique result: 3; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 3"))
                .body("'path'", containsString("/api/ticket"));
    }
    
    
    @Test(timeout = 60000)
    public void test_6_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/ticket/{id}
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/ticket/513")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Ticket with id 513; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Ticket with id 513 (through reference chain: com.app.entity.Ticket$HibernateProxy$HiBEFQNt[\"ticketCode\"])"))
                .body("'path'", containsString("/api/ticket/513"));
    }
    
    
    @Test(timeout = 60000)
    public void test_7_with500() throws Exception {
        
        // Fault100. HTTP Status 500. POST:/api/company
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": -4242818832140431845, " + 
                    " \"name\": \"C\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/company")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("query did not return a unique result: 3; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 3"))
                .body("'path'", containsString("/api/company"));
    }
    
    
    @Test(timeout = 60000)
    public void test_8_with500() throws Exception {
        
        // Fault100. HTTP Status 500. PUT:/api/plane
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": 200, " + 
                    " \"name\": \"O\", " + 
                    " \"company\": { " + 
                    " \"id\": -2391204987768116174, " + 
                    " \"name\": \"\" " + 
                    " } " + 
                    " } ")
                .put(baseUrlOfSut + "/api/plane")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to find com.app.entity.Company with id -2391204987768116174; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.app.entity.Company with id -2391204987768116174"))
                .body("'path'", containsString("/api/plane"));
    }
    
    
    @Test(timeout = 60000)
    public void test_9_with500() throws Exception {
        
        // Fault100. HTTP Status 500. PUT:/api/ticket
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": 270, " + 
                    " \"ticketCode\": \"Juvvu0SVUHJ\", " + 
                    " \"price\": 755 " + 
                    " } ")
                .put(baseUrlOfSut + "/api/ticket")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No message available"))
                .body("'path'", containsString("/api/ticket"));
    }
    
    
    @Test(timeout = 60000)
    public void test_10_with500() throws Exception {
        
        // Fault100. HTTP Status 500. POST:/api/plane
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"nQnI\", " + 
                    " \"numberOfSeats\": 374, " + 
                    " \"companyId\": 667 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/plane")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to find com.app.entity.Company with id 667; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.app.entity.Company with id 667"))
                .body("'path'", containsString("/api/plane"));
    }
    
    
    @Test(timeout = 60000)
    public void test_11_with500() throws Exception {
        
        // Fault100. HTTP Status 500. PUT:/api/route
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"id\": 901523627, " + 
                    " \"name\": \"VFDS8G6\", " + 
                    " \"departureAirport\": { " + 
                    " \"id\": 401, " + 
                    " \"name\": \"X7rPrEtN3\", " + 
                    " \"location\": \"BG\" " + 
                    " } " + 
                    " } ")
                .put(baseUrlOfSut + "/api/route")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Airport with id 401; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Airport with id 401 (through reference chain: com.app.entity.Route[\"departureAirport\"]->com.app.entity.Airport$HibernateProxy$2QExZwpo[\"name\"])"))
                .body("'path'", containsString("/api/route"));
    }
    
    
    @Test(timeout = 60000)
    public void test_12_with500() throws Exception {
        
        // Fault100. HTTP Status 500. POST:/api/flight
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"K\", " + 
                    " \"duration\": 326, " + 
                    " \"planeId\": 618, " + 
                    " \"routeId\": 80 " + 
                    " } ")
                .post(baseUrlOfSut + "/api/flight")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2"))
                .body("'path'", containsString("/api/flight"));
    }
    
    
    @Test(timeout = 60000)
    public void test_13_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/plane/{id}
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/plane/7346547542035295814")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Plane with id 7346547542035295814; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Plane with id 7346547542035295814 (through reference chain: com.app.entity.Plane$HibernateProxy$YB3pkGi3[\"name\"])"))
                .body("'path'", containsString("/api/plane/7346547542035295814"));
    }
    
    
    @Test(timeout = 60000)
    public void test_14_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/flight/{id}
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/flight/1972517884")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Flight with id 1972517884; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Flight with id 1972517884 (through reference chain: com.app.entity.Flight$HibernateProxy$pUJyuPQU[\"name\"])"))
                .body("'path'", containsString("/api/flight/1972517884"));
    }
    
    
    @Test(timeout = 60000)
    public void test_15_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/plane
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/plane")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to find com.app.entity.Company with id 1; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.app.entity.Company with id 1"))
                .body("'path'", containsString("/api/plane"));
    }
    
    
    @Test(timeout = 60000)
    public void test_16_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/airport/{id}
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/airport/872")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Airport with id 872; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Airport with id 872 (through reference chain: com.app.entity.Airport$HibernateProxy$2QExZwpo[\"name\"])"))
                .body("'path'", containsString("/api/airport/872"));
    }
    
    
    @Test(timeout = 60000)
    public void test_17_with500() throws Exception {
        
        // Fault100. HTTP Status 500. DELETE:/api/ticket/{id}
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/ticket/502")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No class com.app.entity.Ticket entity with id 502 exists!"))
                .body("'path'", containsString("/api/ticket/502"));
    }
    
    
    @Test(timeout = 60000)
    public void test_18_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/company/{id}
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/company/952")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Company with id 952; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Company with id 952 (through reference chain: com.app.entity.Company$HibernateProxy$Z64amnsF[\"name\"])"))
                .body("'path'", containsString("/api/company/952"));
    }
    
    
    @Test(timeout = 60000)
    public void test_19_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/flight
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/flight")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.util.ArrayList[0]->com.app.entity.Flight[\"quotaFilledPercentage\"])"))
                .body("'path'", containsString("/api/flight"));
    }
    
    
    @Test(timeout = 60000)
    public void test_20_with500() throws Exception {
        
        // Fault100. HTTP Status 500. DELETE:/api/plane/{id}
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/plane/125")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No class com.app.entity.Plane entity with id 125 exists!"))
                .body("'path'", containsString("/api/plane/125"));
    }
    
    
    @Test(timeout = 60000)
    public void test_21_with500() throws Exception {
        
        // Fault100. HTTP Status 500. DELETE:/api/airport/{id}
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/airport/744")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No class com.app.entity.Airport entity with id 744 exists!"))
                .body("'path'", containsString("/api/airport/744"));
    }
    
    
    @Test(timeout = 60000)
    public void test_22_with500() throws Exception {
        
        // Fault100. HTTP Status 500. POST:/api/airport
        given().accept("*/*")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"W\" " + 
                    " } ")
                .post(baseUrlOfSut + "/api/airport")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("query did not return a unique result: 5; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 5"))
                .body("'path'", containsString("/api/airport"));
    }
    
    
    @Test(timeout = 60000)
    public void test_23_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/route/{id}
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/route/918")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Route with id 918; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Route with id 918 (through reference chain: com.app.entity.Route$HibernateProxy$tZsY4Xyo[\"name\"])"))
                .body("'path'", containsString("/api/route/918"));
    }
    
    
    @Test(timeout = 60000)
    public void test_24_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/ticket
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/ticket")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Flight with id 357; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Flight with id 357 (through reference chain: java.util.ArrayList[0]->com.app.entity.Ticket[\"flight\"]->com.app.entity.Flight$HibernateProxy$pUJyuPQU[\"name\"])"))
                .body("'path'", containsString("/api/ticket"));
    }
    
    
    @Test(timeout = 60000)
    public void test_25_with500() throws Exception {
        
        // Fault100. HTTP Status 500. GET:/api/route
        given().accept("*/*")
                .get(baseUrlOfSut + "/api/route")
                .then()
                .statusCode(500)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500.0))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Could not write JSON: Unable to find com.app.entity.Airport with id 520; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to find com.app.entity.Airport with id 520 (through reference chain: java.util.ArrayList[0]->com.app.entity.Route[\"departureAirport\"]->com.app.entity.Airport$HibernateProxy$2QExZwpo[\"name\"])"))
                .body("'path'", containsString("/api/route"));
    }


}
